name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Introspection01
      id: introspection-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Introspection01
        command: pytest -vk "Introspection01"
        timeout: 20
        max-score: 1

    - name: DataTypes01
      id: datatypes-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes01
        command: 
        timeout: 20
        max-score: 1

    - name: DataTypes02
      id: datatypes-02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes02
        command: pytest -vk "DataTypes02"
        timeout: 20
        max-score: 1

    - name: DataTypes03
      id: datatypes-03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes03
        command: pytest -vk "DataTypes03"
        timeout: 20
        max-score: 1

    - name: DataTypes04
      id: datatypes-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes04
        command: pytest -vk "DataTypes04"
        timeout: 20
        max-score: 1

    - name: DataTypes05
      id: datatypes-05
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes05
        command: pytest -vk "DataTypes05"
        timeout: 20
        max-score: 1

    - name: DataTypes06
      id: datatypes-06
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes06
        command: pytest -vk "DataTypes06"
        timeout: 20
        max-score: 1

    - name: DataTypes07
      id: datatypes-07
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: DataTypes07
        command: pytest -vk "DataTypes07"
        timeout: 20
        max-score: 1

    - name: CommonTools01
      id: commontools-01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: CommonTools01
        command: 
        timeout: 20
        max-score: 1

    - name: CommonTools02
      id: commontools-02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: CommonTools02
        command: 
        timeout: 20
        max-score: 1

    - name: CommonTools03
      id: commontools-03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: CommonTools03
        command: 
        timeout: 20
        max-score: 1

    - name: CommonTools04
      id: commontools-04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: CommonTools04
        command: 
        timeout: 20
        max-score: 1

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTROSPECTION01_RESULTS: "${{steps.introspection-01.outputs.result}}"
        DATATYPES01_RESULTS: "${{steps.datatypes-01.outputs.result}}"
        DATATYPES02_RESULTS: "${{steps.datatypes-02.outputs.result}}"
        DATATYPES03_RESULTS: "${{steps.datatypes-03.outputs.result}}"
        DATATYPES04_RESULTS: "${{steps.datatypes-04.outputs.result}}"
        DATATYPES05_RESULTS: "${{steps.datatypes-05.outputs.result}}"
        DATATYPES06_RESULTS: "${{steps.datatypes-06.outputs.result}}"
        DATATYPES07_RESULTS: "${{steps.datatypes-07.outputs.result}}"
        COMMONTOOLS01_RESULTS: "${{steps.commontools-01.outputs.result}}"
        COMMONTOOLS02_RESULTS: "${{steps.commontools-02.outputs.result}}"
        COMMONTOOLS03_RESULTS: "${{steps.commontools-03.outputs.result}}"
        COMMONTOOLS04_RESULTS: "${{steps.commontools-04.outputs.result}}"
      with:
        runners: introspection-01,datatypes-01,datatypes-02,datatypes-03,datatypes-04,datatypes-05,datatypes-06,datatypes-07,commontools-01,commontools-02,commontools-03,commontools-04